Description: AppConfig for autoscaling of game containers
Resources:
  AppConfigApp:
    Type: AWS::AppConfig::Application
    Properties:
      Name: SyndicateGameContainerAutoScale
  AppConfigEnvironment:
    Type: AWS::AppConfig::Environment
    Properties:
      ApplicationId: !Ref AppConfigApp
      Name: production
  AppConfigConfigProfile:
    Type: AWS::AppConfig::ConfigurationProfile
    Properties:
      ApplicationId: !Ref AppConfigApp
      LocationUri: hosted
      Name: GameContainerAutoScaling
      Validators:
        - Content: |
            {
              "title": "GameContainerAutoScaling",
              "description": "Configuration JSON for GameContainerAutoScaling",
              "type": "object",
              "properties": {
                "min_tasks": {
                  "description": "the minimum number of tasks running",
                  "type": "number"
                },
                "max_task_start_delay_seconds": {
                  "description": "the maximum number of seconds before a game is started before the autoscaler adds a new task",
                  "type": "number"
                }
              },
              "required": [ "min_tasks", "max_task_start_delay_seconds"]
            }
          Type: JSON_SCHEMA
  AppConfigDeploymentStrategy:
    Type: AWS::AppConfig::DeploymentStrategy
    Properties:
      DeploymentDurationInMinutes: 0
      FinalBakeTimeInMinutes: 5
      GrowthFactor: 100
      GrowthType: LINEAR
      Name: Custom.Immediate.Bake5Mins
      ReplicateTo: NONE
  AppConfigConfigVersion:
    Type: AWS::AppConfig::HostedConfigurationVersion
    Properties:
      ApplicationId: !Ref AppConfigApp
      ConfigurationProfileId: !Ref AppConfigConfigProfile
      ContentType: application/json
      Content: |
        {
          "min_tasks": 2,
          "max_task_start_delay_seconds": 8
        }
  AppConfigDeployment:
    Type: AWS::AppConfig::Deployment
    Properties:
      ApplicationId: !Ref AppConfigApp
      ConfigurationProfileId: !Ref AppConfigConfigProfile
      ConfigurationVersion: !Ref AppConfigConfigVersion
      DeploymentStrategyId: !Ref AppConfigDeploymentStrategy
      EnvironmentId: !Ref AppConfigEnvironment
