Resources:
  BungeeVPCInternetGateway:
    Type: AWS::EC2::InternetGateway
  BungeeVPCAttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref BungeeVPC
      InternetGatewayId: !Ref BungeeVPCInternetGateway
  BungeeExternalIP:
    Type: AWS::EC2::EIP
  BungeeECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      ServiceName: cfn-bungee
      Cluster: 'arn:aws:ecs:us-west-2:595508394202:cluster/syndicate-bungee-01'
      DesiredCount: '1'
      EnableExecuteCommand: 'true'
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: bungee-test-01
          ContainerPort: 25565
          TargetGroupArn: !Ref BungeeTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - sg-060a4e1490a93b62c
          Subnets:
            - subnet-0b60606dea2eedb32
      SchedulingStrategy: REPLICA
      TaskDefinition: 'arn:aws:ecs:us-west-2:595508394202:task-definition/bungee:1'
    DependsOn:
      - MinecraftListener
  BungeeLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      SubnetMappings:
        - SubnetId: !Ref SubnetEC2S1JRJR
          AllocationId: !GetAtt BungeeExternalIP.AllocationId
      Type: network
  MinecraftListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
         LoadBalancerArn: !Ref BungeeLoadBalancer
         DefaultActions:
           - Type: forward
             TargetGroupArn: !Ref BungeeTargetGroup
         Port: 25565
         Protocol: "TCP"
  BungeeTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      TargetType: ip
      Protocol: TCP
      Port: 25565
      VpcId: !Ref BungeeVPC
  BungeeVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
  S3EndpointRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref BungeeVPC
  S3EndpointDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: BungeeVPCInternetGateway
    Properties:
       RouteTableId:
         Ref: S3EndpointRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId: Ref! BungeeVPCInternetGateway
  S3EndpointLocalRoute:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 10.0.0.0/16
      GatewayId: String
      InstanceId: String
      LocalGatewayId: String
      NatGatewayId: String
      NetworkInterfaceId: String
      RouteTableId: String
      TransitGatewayId: String
      VpcEndpointId: String
      VpcPeeringConnectionId: String
  S3Endpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - '*'
            Resource:
              - '*'
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref BungeeVPC
    DependsOn:
      - BungeeVPC
  SubnetEC2S1JRJR:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref BungeeVPC
  SSMEndpoint:
  ECRApiEndpoint:
  SecretsManagerEndpoint:
  ECRDKREndpoint:
