Description: SyndicateVPCAndBroker, Create a VPC and an Amazon MQ Broker for Bridge Syndicate.
Resources:
  SyndicateVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SyndicateVPC
  PublicSubnetDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: SyndicateVPCAttachInternetGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref SyndicateVPCInternetGateway
  NatExternalIP:
    Type: AWS::EC2::EIP
  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      ConnectivityType: public
      SubnetId: !Ref SubnetPublic
      AllocationId: !GetAtt NatExternalIP.AllocationId
  NATRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SyndicateVPC
  NATDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref NATRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway
  LambdaNATDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref SyndicateVPCRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway
  SyndicateVPCRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SyndicateVPC
  PeerVPCRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SyndicateVPC
  PeerVPCRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PeerVPCRouteTable
      DestinationCidrBlock: 10.1.0.0/16
      VpcPeeringConnectionId: pcx-0c6802235aace0944
  SyndicateVPCInternetGateway:
    Type: AWS::EC2::InternetGateway
  SyndicateVPCAttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref SyndicateVPC
      InternetGatewayId: !Ref SyndicateVPCInternetGateway
  SubnetBroker:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.255.0/24
      VpcId: !Ref SyndicateVPC
  SubnetLambda:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.254.0/24
      VpcId: !Ref SyndicateVPC
  SubnetPublic:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.253.0/24
      VpcId: !Ref SyndicateVPC
  SubnetRDSc:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.252.0/25
      AvailabilityZone: 'us-west-2c'
      VpcId: !Ref SyndicateVPC
  SubnetRDSd:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.252.128/25
      AvailabilityZone: 'us-west-2d'
      VpcId: !Ref SyndicateVPC
  SubnetMinecraft:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/20
      VpcId: !Ref SyndicateVPC
  SubnetBungee:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.16.0/24
      VpcId: !Ref SyndicateVPC
  SubnetDiscordBot:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.18.0/24
      VpcId: !Ref SyndicateVPC
  SubnetBrokerSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PeerVPCRouteTable
      SubnetId: !Ref SubnetBroker
  DiscordBotSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref NATRouteTable
      SubnetId: !Ref SubnetDiscordBot
  LambdaSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SyndicateVPCRouteTable
      SubnetId: !Ref SubnetLambda
  BungeeSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref NATRouteTable
      SubnetId: !Ref SubnetBungee
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref SubnetPublic
  MinecraftSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref NATRouteTable
      SubnetId: !Ref SubnetMinecraft
  HTTPIngresSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound http and https
      VpcId: !Ref SyndicateVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        ToPort: 80
        FromPort: 80
        CidrIp: 10.0.0.0/16
      - IpProtocol: tcp
        ToPort: 443
        FromPort: 443
        CidrIp: 10.0.0.0/16
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
  SSHIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound ssh traffic
      VpcId: !Ref SyndicateVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        ToPort: 22
        FromPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
    DependsOn:
      - SyndicateVPC
  RabbitIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound rabbitmq
      VpcId: !Ref SyndicateVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        ToPort: 5672
        FromPort: 5671
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 10.0.0.0/16
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 10.1.16.0/24
    DependsOn:
      - SyndicateVPC
  MinecraftIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound minecraft
      VpcId: !Ref SyndicateVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        ToPort: 25565
        FromPort: 25565
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
    DependsOn:
      - SyndicateVPC
  PostgresIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound postgres
      VpcId: !Ref SyndicateVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        ToPort: 5432
        FromPort: 5432
        CidrIp: 10.0.0.0/16
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
  DynamoDBVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - '*'
            Resource:
              - '*'
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.dynamodb'
      VpcId: !Ref SyndicateVPC
      RouteTableIds:
        - !Ref SyndicateVPCRouteTable
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - '*'
            Resource:
              - '*'
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref SyndicateVPC
      RouteTableIds:
        - !Ref SyndicateVPCRouteTable
        - !Ref NATRouteTable
  SyndicateBroker:
    Type: AWS::AmazonMQ::Broker
    Properties:
      AutoMinorVersionUpgrade: 'false'
      BrokerName: SyndicateRabbitBroker
      DeploymentMode: SINGLE_INSTANCE
      EngineType: RabbitMQ
      EngineVersion: 3.8.11
      HostInstanceType: mq.t3.micro
      Logs:
        General: 'true'
      MaintenanceWindowStartTime:
        DayOfWeek: Monday
        TimeOfDay: '22:45'
        TimeZone: America/Los_Angeles
      PubliclyAccessible: 'false'
      SecurityGroups:
        - !Ref RabbitIngressSecurityGroup
      SubnetIds:
        - !Ref SubnetBroker
      Users:
        - ConsoleAccess: 'true'
          Password: AmazonMqPassword
          Username: AmazonMqUsername
  SyndicateECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: SyndicateECSCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
  SyndicateBungeeTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: arn:aws:iam::595508394202:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: SyndicateBungeeTask
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/SyndicateBungeeTask
              awslogs-region: us-west-2
              awslogs-stream-prefix: ecs
          PortMappings:
            - HostPort: 25565
              Protocol: tcp
              ContainerPort: 25565
          Image: 595508394202.dkr.ecr.us-west-2.amazonaws.com/syn-bungee-servers:latest
          Environment:
            - Name: RABBIT_URI
              Value: !ImportValue
                'SyndicateVPCAndBroker-AmqpEndpoint'
            - Name: LOBBY_HOSTNAME
              Value: !GetAtt LobbyLoadBalancer.DNSName
            - Name: SYNDICATE_KICK_HOST
              Value: www.bridgesyndicate.gg
            - Name: SYNDICATE_PROXY_DESCRIPTION
              Value: 'Bridge Syndicate Lobby'
      PlacementConstraints: []
      Memory: 1024
      TaskRoleArn: arn:aws:iam::595508394202:role/syndicate-bridge-dev-server-task-role
      Family: SyndicateBungeeTaskDefinition
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '512'
  SyndicateBungeeECSServiceV03:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: SyndicateBungeeECSServiceV03
      Cluster: !Ref SyndicateECSCluster
      DesiredCount: 0
      EnableExecuteCommand: 'true'
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: SyndicateBungeeTask
          ContainerPort: 25565
          TargetGroupArn: !Ref BungeeLoadBalancerTargetGroupV03
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref MinecraftIngressSecurityGroup
          Subnets:
            - !Ref SubnetBungee
      SchedulingStrategy: REPLICA
      TaskDefinition: !Ref SyndicateBungeeTaskDefinition
    DependsOn:
      - BungeeLoadBalancerMinecraftListenerV03
  BungeeLoadBalancerElasticIPV03:
    Type: AWS::EC2::EIP
  BungeeLoadBalancerV03:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      SubnetMappings:
        - SubnetId: !Ref SubnetPublic
          AllocationId: !GetAtt BungeeLoadBalancerElasticIPV03.AllocationId
      Type: network
  BungeeLoadBalancerTargetGroupV03:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: ip
      Protocol: TCP
      Port: 25565
      VpcId: !Ref SyndicateVPC
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckIntervalSeconds: 10
  BungeeLoadBalancerMinecraftListenerV03:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
         LoadBalancerArn: !Ref BungeeLoadBalancerV03
         DefaultActions:
           - Type: forward
             TargetGroupArn: !Ref BungeeLoadBalancerTargetGroupV03
         Port: 25565
         Protocol: "TCP"
  LobbyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      SubnetMappings:
        - SubnetId: !Ref SubnetMinecraft
      Type: network
      Scheme: internal
  LobbyLoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: ip
      Protocol: TCP
      Port: 25565
      VpcId: !Ref SyndicateVPC
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckIntervalSeconds: 10
  LobbyLoadBalancerMinecraftListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
         LoadBalancerArn: !Ref LobbyLoadBalancer
         DefaultActions:
           - Type: forward
             TargetGroupArn: !Ref LobbyLoadBalancerTargetGroup
         Port: 25565
         Protocol: "TCP"
  SyndicateLobbyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: arn:aws:iam::595508394202:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: SyndicateLobbyTask
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/SyndicateLobbyTask
              awslogs-region: us-west-2
              awslogs-stream-prefix: ecs
          PortMappings:
            - HostPort: 25565
              Protocol: tcp
              ContainerPort: 25565
          Image: 595508394202.dkr.ecr.us-west-2.amazonaws.com/syn-lobby:latest
      PlacementConstraints: []
      Memory: 1024
      TaskRoleArn: arn:aws:iam::595508394202:role/syndicate-bridge-dev-server-task-role
      Family: SyndicateLobbyTaskDefinition
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '512'
  SyndicateLobbyECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: SyndicateLobbyECSServiceV03
      Cluster: !Ref SyndicateECSCluster
      DesiredCount: 0
      EnableExecuteCommand: 'true'
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: SyndicateLobbyTask
          ContainerPort: 25565
          TargetGroupArn: !Ref LobbyLoadBalancerTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref MinecraftIngressSecurityGroup
          Subnets:
            - !Ref SubnetMinecraft
      SchedulingStrategy: REPLICA
      TaskDefinition: !Ref SyndicateLobbyTaskDefinition
    DependsOn:
      - LobbyLoadBalancerMinecraftListener
  SyndicateBridgeTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: arn:aws:iam::595508394202:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: SyndicateBridgeTask
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/SyndicateBridgeTask
              awslogs-region: us-west-2
              awslogs-stream-prefix: ecs
          PortMappings:
            - HostPort: 25565
              Protocol: tcp
              ContainerPort: 25565
          Environment:
            - Name: SYNDICATE_ENV
              Value: production
            - Name: SYNDICATE_MATCH_QUEUE_NAME
              Value: syndicate_production_games
          Image: 595508394202.dkr.ecr.us-west-2.amazonaws.com/syn-bridge-servers:latest
      PlacementConstraints: []
      Memory: 1024
      TaskRoleArn: arn:aws:iam::595508394202:role/syndicate-bridge-dev-server-task-role
      Family: SyndicateBridgeTaskDefinition
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '512'
  SyndicateBridgeECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: SyndicateBridgeECSService
      Cluster: !Ref SyndicateECSCluster
      DesiredCount: 0
      EnableExecuteCommand: 'true'
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref MinecraftIngressSecurityGroup
          Subnets:
            - !Ref SubnetMinecraft
      SchedulingStrategy: REPLICA
      TaskDefinition: !Ref SyndicateBridgeTaskDefinition
  SyndicateDiscordBotTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: arn:aws:iam::595508394202:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: SyndicateDiscordBotTask
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/SyndicateDiscordBotTask
              awslogs-region: us-west-2
              awslogs-stream-prefix: ecs
          Environment:
            - Name: SYNDICATE_ENV
              Value: production
            - Name: POSTGRES_HOST
              Value: !GetAtt SyndicateRankedRDSInstance.Endpoint.Address
          Image: 595508394202.dkr.ecr.us-west-2.amazonaws.com/syn-bot:latest
      PlacementConstraints: []
      Memory: 1024
      TaskRoleArn: arn:aws:iam::595508394202:role/syndicate-discord-bot-task-role
      Family: SyndicateDiscordBotTaskDefinition
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '512'
  SyndicateDiscordBotECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: SyndicateDiscordBotECSService
      Cluster: !Ref SyndicateECSCluster
      DesiredCount: 0
      EnableExecuteCommand: 'true'
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref SubnetDiscordBot
      SchedulingStrategy: REPLICA
      TaskDefinition: !Ref SyndicateDiscordBotTaskDefinition
  SyndicateRankedRDSInstanceSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: SyndicateRankedRDSInstanceSubnetGroup
      SubnetIds:
        - !Ref SubnetRDSc
        - !Ref SubnetRDSd
  SyndicateRankedRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 10
      BackupRetentionPeriod: 14
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: !Ref SyndicateRankedRDSInstanceSubnetGroup
      DeleteAutomatedBackups: 'false'
      Engine: postgres
      EngineVersion: 12.8
      MasterUsername: AmazonPgUsername
      MasterUserPassword: AmazonPgPassword
      StorageType: standard
      VPCSecurityGroups:
        - !Ref PostgresIngressSecurityGroup
Outputs:
  SyndicateVPC:
    Description: The Syndicate VPC
    Value: !Ref SyndicateVPC
    Export:
      Name: !Sub '${AWS::StackName}-SyndicateVPCId'
  AmqpEndpoints:
    Description: AMQP endpoint that clients should attach to
    Value: !Join [ ",", !GetAtt SyndicateBroker.AmqpEndpoints ]
    Export:
      Name: !Sub '${AWS::StackName}-AmqpEndpoint'
  RabbitIngressSecurityGroupId:
    Description: Name id the ingress security group for Rabbit
    Value:  !GetAtt RabbitIngressSecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-RabbitIngressSecurityGroupId'
  SubnetLambdaId:
    Description: Id of the subnet for Lambda
    Value:  !Ref SubnetLambda
    Export:
      Name: !Sub '${AWS::StackName}-SubnetLambdaId'
  HTTPIngressSecurityGroupId:
    Description: Id of the ingress security group for HTTP
    Value:  !GetAtt HTTPIngresSecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-HTTPIngressSecurityGroupId'
  PostgresIngressSecurityGroupId:
    Description: Id of the ingress security group for Postgres
    Value:  !GetAtt PostgresIngressSecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-PostgresIngressSecurityGroupId'
  RDSEndpoint:
    Description: Postgres endpoint
    Value: !GetAtt SyndicateRankedRDSInstance.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-RDSEndpoint'
