Description: Crate an Amazon MQ Broker for Bridge
Resources:
  SyndicateVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
  SubnetBroker:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.255.0/24
      VpcId: !Ref SyndicateVPC
  RabbitIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound rabbitmq
      VpcId: !Ref SyndicateVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        ToPort: 5672
        FromPort: 5671
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
    DependsOn:
      - SyndicateVPC
  SyndicateBroker:
    Type: 'AWS::AmazonMQ::Broker'
    Properties:
      AutoMinorVersionUpgrade: 'false'
      BrokerName: SyndicateRabbitBroker
      DeploymentMode: SINGLE_INSTANCE
      EngineType: RabbitMQ
      EngineVersion: 3.8.11
      HostInstanceType: mq.t3.micro
      Logs:
        General: 'true'
      MaintenanceWindowStartTime:
        DayOfWeek: Monday
        TimeOfDay: '22:45'
        TimeZone: America/Los_Angeles
      PubliclyAccessible: 'false'
      SecurityGroups:
        - !Ref RabbitIngressSecurityGroup
      SubnetIds:
        - !Ref SubnetBroker
      Users:
        - ConsoleAccess: 'true'
          Password: AmazonMqPassword
          Username: AmazonMqUsername
Outputs:
  SyndicateVPC:
    Description: The Syndicate VPC
    Value: !Ref SyndicateVPC
    Export:
      Name: !Sub '${AWS::StackName}-SyndicateVPC-Id'
  AmqpEndpoints:
    Description: AMQP endpoint that clients should attach to
    Value: !Join [ ",", !GetAtt SyndicateBroker.AmqpEndpoints ]
    Export:
      Name: !Sub '${AWS::StackName}-AmqpEndpoint'
  RabbitIngressSecurityGroupId:
    Description: Name id the ingress security group for Rabbit
    Value:  !GetAtt RabbitIngressSecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-RabbitIngressSecurityGroupId'
  SubnetBrokerId:
    Description: Name id of the subnet for Rabbit
    Value:  !Ref SubnetBroker
    Export:
      Name: !Sub '${AWS::StackName}-SubnetBrokerId'
